Remove dependency on "udisks", use /sys/class/block instead
Also, allow user to specify a specific partition, not just a whole drive.

diff --git a/lba2file b/lba2file
--- a/lba2file
+++ b/lba2file
@@ -5,7 +5,7 @@
 
 # This is the opposite of `hdparm --fibmap /foo/bar`
 
-# B9 Feburary 2019
+# B9 May 2020
 
 if [[ "$1" == "-b" ]]; then
     BYTESFLAG=Byte
@@ -18,47 +18,71 @@ if [[ $# -lt 2 ]]; then
     exit 1
 fi
 
+if [[ $(id -u) -ne 0 ]]; then
+    echo "Please run as root using 'sudo $@'" >&2
+    exit 1
+fi
+
 lba=$1
 drive=$2
+drive=${drive#/dev/}		# Remove /dev/ prefix, if any.
 
+if [[ "$drive" =~ ^(.*)[0-9]$ ]]; then    # Either user specified a partition.
+    searchparts="/sys/class/block/$drive"
+    drive=${BASH_REMATCH[1]}
+else				     # Or user specified a drive.
+    shopt -s nullglob		     # Don't use '?' literally.
+    searchparts=$(eval echo /sys/class/block/${drive}?)
+fi
 
-for partition in ${drive}?; do
-    info=$(udisks --show-info $partition)
-    if ! e2blocksize=$(tune2fs -l $partition 2>/dev/null |
-			      grep '^Block size' | egrep -o '[0-9]+'); then
-	continue		# Not an Ext2/3/4 partition
+for partition in $searchparts; do
+    device=/dev/${partition#/sys/class/block/}
+    cd "$partition" || continue
+    start=$(cat "$partition/start")
+    partitionsize=$(cat "$partition/size")
+    hwsectorsize=$(cat "/sys/class/block/$drive/queue/hw_sector_size")
+
+    # Typically: e2blocksize==4096, hwsectorsize==512
+    # Example: start=1048576, partitionsize=640133980160
+    # Do a sanity check.
+    if [[ -z "$start" || -z "$partitionsize" || -z "$hwsectorsize" ]]; then
+	echo "Error reading data for $device" >&2
+	continue
     fi
-    offset=$(grep '^    offset:' <<< "$info" | egrep -o '[0-9]+')
-    partitionsize=$(grep '^  size:' <<< "$info" | egrep -o '[0-9]+')
-    diskblocksize=$(grep '^  block size:' <<< "$info" | egrep -o '[0-9]+')
 
-    # Typically: e2blocksize==4096, diskblocksize==512
-    # Example: offset=1048576, partitionsize=640133980160
+    # Scale everything to bytes since we'll use that for debugfs.
+    start=$((start * hwsectorsize))
+    partitionsize=$((partitionsize * hwsectorsize))
+
+    # If not using byte flag, scale the address, too.
     if [[ -z "$BYTESFLAG" ]]; then
-	byteaddress=$((lba * diskblocksize))
+	byteaddress=$((lba * hwsectorsize))
     else
 	byteaddress=$lba
     fi
-    if [[ $byteaddress -lt $offset ||
-	  $byteaddress -ge $((offset+partitionsize)) ]]; then
-	echo "Not in $partition"
+    if [[ $byteaddress -lt $start ||
+	  $byteaddress -ge $((start+partitionsize)) ]]; then
+	#echo "Address $byteaddress is not within $partition"
 	continue 		# Not in this partition
     fi
 
-    # Shift to byteaddress within partition
-    partitionbyteaddress=$((byteaddress - offset))
+    if ! e2blocksize=$(tune2fs -l $device 2>/dev/null |
+			   grep '^Block size' | egrep -o '[0-9]+'); then
+	echo "Skipping $device, not an Ext2/3/4 partition" 
+	continue
+    fi
 
     # Scale address by filesystem blocksize to find filesystem block number
-    e2blockaddress=$((partitionbyteaddress / e2blocksize))
+    e2blockaddress=$(( (byteaddress - start) / e2blocksize))
     
     Sector=${BYTESFLAG:-Sector}
-    echo "Disk $Sector $lba is at filesystem block $e2blockaddress in $partition"
-    inode=$(debugfs -R "icheck $e2blockaddress" $partition 2>/dev/null |
+    echo "Disk $Sector $lba is at filesystem block $e2blockaddress in $device"
+    inode=$(debugfs -R "icheck $e2blockaddress" $device 2>/dev/null |
 		   tail -1 | cut -f2)
     if [[ "$inode" && "$inode" != "<block not found>" ]]; then
 	echo "$Sector is used by inode $inode"
 	echo "Searching for filename(s)..."
-	debugfs -R "ncheck $inode" $partition 2>/dev/null
+	debugfs -R "ncheck $inode" $device 2>/dev/null
     else
 	echo "$Sector is not in use."
     fi
